version: "2"
services:
  myfi-app:
    image: myfi-app:latest
    container_name: myfi
    networks:
      - nginx
    ports:
      - "8080:8080"
    volumes:
      - /data/myfi/data:/data
    restart: unless-stopped

networks:
  nginx:
    external:
      name: nginx
